apiVersion: v1
kind: Service
metadata:
  name: react-nodejs-service
spec:
  selector:
    app: react-nodejs-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # You may need to change this depending on your environment
